nimblehq/flutter-templates

.gitignore
README.md
ios/Flutter/Debug.xcconfig
ios/Flutter/Release.xcconfig
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/production.xcscheme
ios/Runner.xcodeproj/xcshareddata/xcschemes/staging.xcscheme
ios/Runner.xcworkspace/contents.xcworkspacedata
ios/Runner/Info.plist

Close #3
Having different app variants/flavors is essential to allow flexible configuration in between staging/production environments.
This part is for iOS. 🙏
- Setup 2 variants of setup as default:
- Staging
- Production
- Config the app name for each flavor.
- Config build actions to provide the keys that can be configured to be different in Staging/Production.
https://user-images.githubusercontent.com/60863885/130412182-d0d6b9a1-e964-47a2-908a-fe608b5039b3.mp4

[3] Setup flavors for iOS

---

pubspec.yaml

A simple bump version commmit
n/a
n/a

Bump version 0.1.0 (2)

---

pubspec.yaml

Bump version before development on 0.2.0 started

Bump version for development v0.2.0 (3)

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/story_template.md
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/release_template.md

We need to update to use the latest git templates and set the list of code reviewers.
N/A

[Chore] Update git templates and code reviewer list

---

README.md
integration_test/my_home_page_test.dart
integration_test/real_app_test.dart
integration_test/utils/test_util.dart
lib/main.dart
pubspec.lock
pubspec.yaml
test_driver/integration_test.dart

Close #8 
- Ensure all the basic requirement for unit testing is set up (integration_test API, test directory).
- Create a basic test case as a showcase to the developer who will use this template.
I remove `asset/videos` and `asset/svg` since that directories don't exist.
https://user-images.githubusercontent.com/60863885/134310436-6403f3ec-c92d-428a-878a-350b37be131e.mov

[#8] Setup integration test and dependencies

---

pubspec.yaml

Bump version v0.3.0 (3) to develop

---

pubspec.yaml

Bump version for development: 0.4.0 (5)

---

Makefile
README.md
scripts/setup.py
scripts/test.py

https://github.com/nimblehq/flutter_templates/issues/25
Currently, when initializing a new project using 'make' command, we have 3 options: PACKAGE_NAME (to set app id), PROJECT_NAME (to set project name), APP_NAME (to set app name). There is no option to set the initial app version (i.e. 0.1.0) from the current template app version (i.e. 0.3.0).
- Add option to init `app_version` and `build_number` in Make
- Update `make` command README.
Having a check on the new update:
```
➜  flutter_templates git:(develop) ✗ make init PACKAGE_NAME=co.nimblehq.admin PROJECT_NAME=admin_app APP_NAME=Manh APP_VERSION=2.2. BUILD_NUMBER=122    
.venv/bin/python3 ./scripts/setup.py --project_path /Users/manhtran/Desktop/nimble/github/flutter_templates --package_name co.nimblehq.admin --project_name admin_app …
```

[#25] As a user, I have an option to initialize the app version when initializing new project

---

.github/workflows/test.yml
test/api/repository/credential_repository_test.dart

https://github.com/nimblehq/flutter_templates/issues/30
https://github.com/nimblehq/flutter_templates/issues/32
We need the CI to validate our integration continuously.
We need to add a `flutter analyze` step to CI workflow to ensure the code quality.
- Clean up all project lint warnings.
- Update CI workflow to have flutter analyze step in Github workflow.
- Add a `test` workflow to check code formatting, static code analyzing, and unit testing.
- A `test` workflow should be run properly on Github Action.

[#30][#32] Setting up CI for the project

---

pubspec.yaml

Bump version v0.6.0 (7) for develop
n/a
n/a

Bump version v0.6.0 (7) for develop

---

Makefile
scripts/setup.py

https://github.com/nimblehq/flutter_templates/issues/66
After moving the Flutter project into `.template` directory, the script for initializing a new project will be failed to run accordingly.
- Update project path to `flutter_templates/.template/`
- After initializing a new project, we move the project from `.template/` to `flutter_templates/` and clean up the template.
- Please ignore the error from `test.py`. I will fix it in #56 🙇 
https://user-images.githubusercontent.com/60863885/162919082-5f8cd57e-bc87-4b65-aec7-aa500915bf8c.mov
The new app is runnable.

[#66] As a developer, I can update the init script to generate a new project from `.template` directory

---

.template/pubspec.yaml

[CHORE] Pump version to 0.7.0

---

.github/wiki/Deployment.md
.github/workflows/publish_docs_to_wiki.yml

https://github.com/nimblehq/flutter_templates/issues/76
Make Github Wiki automated and easy to code review/create PR.
- Reuse the workflows https://github.com/nimblehq/github-actions-workflows/blob/develop/.github/workflows/publish_wiki.yml
n/a

[#76] Add workflows for publishing docs to WIKI

---

.github/CODEOWNERS
.github/workflows/test.yml
scripts/setup.py

https://github.com/nimblehq/flutter_templates/issues/64
We don't have any CI for verifying the init script is still working correctly.
Create a workflow in CI to verify the template is working correctly:
- Add a step to run the command `make run`
- CI fails if a test fails.
- Trigger the workflow on `push` and `pull request`.
- We need to skip requesting [enquiries](https://pypi.org/project/enquiries/) on CI.

[#64] As a developer, I can run the test for template in CI

---

.template/pubspec.yaml

[CHORE] Bump version to 0.8.0

---

.template/pubspec.yaml

[CHORE] Bump version to 0.9.0

---

.gitignore
.template/.github/workflows/test.yml
.template/README.md
.template/codecov.yml

https://github.com/nimblehq/flutter_templates/issues/21
We need to keep our test coverage under observation. This helps the team to always be aware of new code being added are tested thoroughly before getting out to be used by someone else.
- Add codecov setup into `.template` project.
- Add sample CodeCov config for `private` repository
Since we moved the main project into [.template](https://github.com/nimblehq/flutter_templates/tree/develop/.template) folder, we need to add support executing `.template` project CI/CD in following tasks, i.e. https://github.com/nimblehq/flutter_templates/issues/47. Please checkout the last Pow from [this PR](https://github.com/nimblehq/flutter_templates/pull/45) 🙏 :
- CodeCov integration https://app.codecov.io/gh/nimblehq/flutter_templates/commits

[#21] Add codecov to the ci/cd pipeline of the project

---

.template/pubspec.yaml

[CHORE] Bump version to 1.0.0

---

.template/integration_test/my_home_page_test.dart
.template/integration_test/utils/test_util.dart
.template/lib/main.dart
.template/pubspec.lock
.template/pubspec.yaml

https://github.com/nimblehq/flutter_templates/issues/96
- Add go_router package.
- Setup `GoRouter` for template app.
- Create `Page1Screen` and `Page2Screen` to demonstrate the usage of GoRouter.
Close #96 
- [Go Router page](https://gorouter.dev/)
- Tutorial: https://www.raywenderlich.com/28987851-flutter-navigator-2-0-using-go_router
- The different between `go` and `push` in go_router: https://codewithandrea.com/articles/flutter-navigation-gorouter-go-vs-push/
https://user-images.githubusercontent.com/60863885/178691800-2613d0be-0c66-4cee-a79e-f285ea0f9d78.mp4

[#96] Add go_router as a main navigator

---

.template/pubspec.yaml

[Chore] Bump version 1.2.0

---

.template/lib/di/interceptor/app_interceptor.dart

https://github.com/nimblehq/flutter_templates/issues/100
- Create refresh token function
- Inside `AppInterceptor`, check status code for `HttpStatus.forbidden` or `HttpStatus.unauthorized`, we will do the refresh token
N/A

[#100] Check unauthorized error and create refresh token function

---

.template/pubspec.yaml

[Chore] Bump version 1.3.0

---

.github/workflows/bump_version.yml

https://github.com/nimblehq/flutter_templates/issues/102
Create a github action to bump version automatically
Automate the process for new pull request creating to bump new version after each release:
- Checkout.
- Bump the new version.
- Commit, push & create a new pull request for new version bumping.
https://github.com/nimblehq/flutter_templates/pull/126/files
https://user-images.githubusercontent.com/88996251/209756853-68590462-b491-480c-ae5b-5415524f2c2b.mov

[#102] Automate New version bumping by Github action

---

.template/ios/Podfile
.template/ios/Podfile.lock
.template/lib/utils/wrappers/permission_wrapper.dart
.template/pubspec.lock
.template/pubspec.yaml

https://github.com/nimblehq/flutter_templates/issues/101
- Apply to use https://pub.dev/packages/permission_handler
- Add a base Permission Wrapper
- Add a base Permission Wrapper with a few basic permission such as: `Camera`, `Gallery`, `OpenAppSetting`
N/A

[#101] Add permission handler to request app permissions

---

.github/workflows/test.yml
.template/.github/workflows/test.yml
.template/analysis_options.yaml

- Solves #137
- We need to add some CI steps to verify generated project by the script:
- Code generator
- Check for any formatting issues
- Statically analyze the Dart code for any errors
- Run tests.
- The Flutter SDK version in CI should be upgraded to match with the config in `pubspec.yml` -> latest **Flutter 3.3.10, Dart 2.18.6** (https://docs.flutter.dev/development/tools/sdk/releases?tab=linux).
- We need to add `analysis-options` exclusion config for generated files.
All additional CI steps have been passed to verify the generated project ✅ https://github.com/nimblehq/flutter_templates/actions/runs/3889528310/jobs/6637857457

[#137] Add CI steps to verify the "generated project" by the script

---

.template/analysis_options.yaml

- Solves #149
Exclude the following generated files from being analyzed when running `flutter analyze .`
- `lib/**.gen.dart`
- `lib/**.config.dart`
N/A
There are no `.gen` and `.config` files being analyzed when running `flutter analyze .` command
```
chorn@Chornys-MacBook-Pro .template % flutter analyze . -v                                                                                 
[  +38 ms] executing: sysctl hw.optional.arm64
[   +8 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[   +2 ms] executing: [/Users/chorn/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e3c29ec00c9c825c891d75054c63fcc46454dca1
[        ] executing: …
```

[#149] Add missing Flutter generated files to analysis_options exclusion config

---

bricks/template/brick.yaml

- Solves #155
- Define variables for `template` brick: app_name, project_name, package_name, app_version, build_number.
- Replace the corresponding data with the variables from the brick.
- Prerequisite: Mason installed, FVM installed.
- Steps to generate the brick:
- `mason get`: fetch the brick.
- `mason make template -o generated/`: Generate the brick to the `generated/` directory.
After generating the brick to a new Flutter project, we must create: `.env` and `.env.staging` files
Run the new project:
- `fvm flutter pub get`
- `fvm flutter pub run build_runner build --delete-conflicting-outputs`
- `fvm flutter run --flavor staging`
Generated log:
```
~/De/n/g/flutter_templates  feature/155-…ation-part-2  mason make template -o generated/ …
```

[#155] [Part 2] Initialize Mason script & configuration

---

bricks/template/__brick__/template/android/app/build.gradle
bricks/template/__brick__/template/android/app/src/debug/AndroidManifest.xml
bricks/template/__brick__/template/android/app/src/main/AndroidManifest.xml
bricks/template/__brick__/template/android/app/src/main/kotlin/{{package_name.pathCase()}}/MainActivity.kt
bricks/template/__brick__/template/android/app/src/main/res/values/strings.xml
bricks/template/__brick__/template/android/app/src/profile/AndroidManifest.xml
bricks/template/__brick__/template/android/app/src/staging/res/values/strings.xml

- Solves #156
- Migrate Android module to mason: `package_name`, `app_name`.
- Prerequisite: `Mason` installed.
- Steps to generate the brick:
- `mason get`: fetch the brick.
- `mason make template -o generated/`: Generate the brick to the `generated/` directory.
```
mason make template -o generated/                                       
? Project name? (your_project_name) Demo
? Package name? (co.nimblehq.template) vn.luongvo.demo
? App name? (Your App Name) DemoApp
? App version? (0.1.0) 0.1.0
? Build number? (1) 1
✓ Generated 160 files. (2.7s)
created generated/template/test_driver/integration_test.dart
created generated/template/integration_test/utils/test_util.dart
created generated/template/integration_test/real_app_test.dart
created …
```

[#156] [Generate project with Mason] Migrate Android project module generating step

---

bricks/template/__brick__/{{project_name.snakeCase()}}/build.yaml
bricks/template/brick.yaml
mason-config.json

- Solves #188 
- Add `json_format` variable  and all options to Mason.
- Replace the hardcode `field_rename`'s value with `json_format`'s value.
- This is the last part of migration from old Python script.
- We can select a choice from multiple choices.
https://github.com/nimblehq/flutter-templates/assets/60863885/5bfc648c-ec5c-4bdb-8926-ac7f461b8998
```
? Project name? (your_project_name) your_project_name
? Package name? (co.nimblehq.template) co.nimblehq.template
? App name? (Your App Name) Your App Name
? App version? (0.1.0) 0.1.0
? Build number? (1) 1
? Your default Json formatting? pascal
✓ Made brick template (0.9s)
✓ Generated 123 file(s):
/Users/tranmanh/Desktop/nimble/github/flutter_templates/.DS_Store (identical)
/Users/tranmanh/Desktop/nimble/github/flutter_templates/your_proj …
```

[#188] [Generate project with Mason] Migrate the "json_serializable.field_rename" setting

---

README.md
bricks/template/__brick__/{{project_name.snakeCase()}}/README.md
bricks/template/__brick__/{{project_name.snakeCase()}}/build.yaml
bricks/template/__brick__/{{project_name.snakeCase()}}/codecov.yml
sample/codecov.yml

- Solves #110
- Solves #180
- Solves #173
- Add a new `Features` section to describe the template's supported features & components at the root README.
- Update the template project's README content with built-in commands + removed the meaningless `Clone the repository` section.
- Move the Codecov's Teambot setup comment inside the codecov.yml config file.
The Codecov integration will soon be moved out to be an optional feature #237
- The root template's README https://github.com/nimblehq/flutter-templates/blob/feature/110-add-supported-features-components-doc/README.md
- The template project's README https://github.com/nimblehq/flutter-templates/blob/feature/110-add-supported-features-components-doc/bricks/template/__brick__/%7B%7Bproject_name.snakeCase()%7D%7D/README.md

[#110] [#180] [#173] Add documentation for template supported features & components

---

.github/workflows/android_deploy_staging.yml

Note: for a release PR, append this parameter `?template=release_template.md` to the current URL to apply the release PR
template, e.g. `{Github PR URL}?template=release_template.md`
--
- Close #
Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.
Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.
Show us the implementation: screenshots, GIFs, etc.

[IGNORE][TEST] Ignore please

---

.github/workflows/android_deploy_staging.yml

https://github.com/nimblehq/flutter-templates/milestone/22
- #245 
- #268
- #239
- N/A

[TEST] Ignore please

---

.github/workflows/android_deploy_staging.yml

Note: for a release PR, append this parameter `?template=release_template.md` to the current URL to apply the release PR
template, e.g. `{Github PR URL}?template=release_template.md`
--
- Close #
Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.
Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.
Show us the implementation: screenshots, GIFs, etc.

[IGNORE][#198] Add test staging

---

.github/workflows/android_deploy_production.yml
.github/workflows/android_deploy_staging.yml

https://github.com/nimblehq/flutter-templates/milestone/22
- #245 
- #268
- #239
- N/A

[IGNORE] Test merge
