- .gitignore
- Makefile
- README.md
- scripts/setup.py
- scripts/test.py
https://github.com/nimblehq/flutter_templates/issues/2
Once checking out the project from the main branch, we should make the process to initialize the project intuitively.
- Allow the user to name their project.
- Allow the user to name their project package name.
- How to use:
- On the project level, we run one command to update the package name and the project name at the same time. It is: `make init PACKAGE_NAME=${com.example} PROJECT_NAME=${project_name} APP_NAME="{Your App Name}"`
- If not defining `PACKAGE_NAME`, `APP_NAME` or `PROJECT_NAME`, we will reuse the old name
- There are some prerequisite steps that are included in `Makefile` also. They are: `install python3` and `install an isolated environment for Python3`. If we want to check this step, just run `make prepare-dev`. If …
> [#2] As a user, I can initialize the project with a 'make' command

- pubspec.lock
- pubspec.yaml
https://github.com/nimblehq/flutter_templates/issues/34
- Upgrade min SDK from 2.12.0 to 2.16.1
- Run `flutter pub upgrade --null-safety` to upgrade all packages automatically
- Run project without warning
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 586ms
[INFO] Initializing inputs
FlutterGen v4.1.6
FlutterGen Loading ... pubspec.yaml
[INFO] Reading cached asset graph...
Generated: /Users/macbookpro/Nimble/NimbleFlutter/flutter_templates/lib/gen/assets.gen.dart
Generated: /Users/macbookpro/Nimble/NimbleFlutter/flutter_templates/lib/gen/fonts.gen.dart
FlutterGen finished.
[INFO] Reading cached asset graph completed, took 338ms
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 749ms
[INFO] …
```
> [#34] Update SDK and dependencies

- Makefile
- build.yaml
- scripts/setup.py
https://github.com/nimblehq/flutter_templates/issues/43
- Add default `build.yaml` file
- Add a `json_serializable.field_rename` selection when executing `make run..` 
n/a
https://user-images.githubusercontent.com/17875522/159622644-a901a773-4b11-4a05-bbc3-30b336ebb488.mp4
> [#43] Add the config for auto renaming the `json_serializable` variable as a snake case when building the generated files

- .github/CODEOWNERS
- Rework the `CODEOWNERS` in the subdirectory `.github` to follow the standardized format used on all project templates.
- Reorder the list of team members in alphabetical order.
All project template repositories now have official leads so it is crucial to have it documented.
> Update the project's maintainers info

- android/app/build.gradle
- ios/Runner.xcodeproj/project.pbxproj
https://github.com/nimblehq/flutter_templates/issues/37
Every project defines the minimum OS version for the app, so it can limit the deprecated APIs and features that no longer exist. The min OS version should follow the market trend to target as much audience as possible.
So we should update minSDK for Android is 23 and iOS is 10.
We will not able to run on any device that has SDK and iOS lower than min version.
N/A
> [#37] Update min Android SDK 23 and iOS 10

- Makefile
- scripts/setup.py
- scripts/test.py
https://github.com/nimblehq/flutter_templates/issues/56
After initializing the project by using init script, the test cases run failed but the project works without any issue. The issue might come from the test itself.
- We create one more env var `RUNNING_TEST_MODE` to separate to 2 cases:
- Run `make test` independently. -> `.template` path is still kept in this case.
- Run `make run` -> After init script successfully, `.template` path should be removed.
https://user-images.githubusercontent.com/60863885/166907360-b12ef4ff-3ced-4e1c-98d9-f8dac664b5d5.mov
> [#56] Fix test cases failed for init script

- .github/wiki/Deployment.md
https://github.com/nimblehq/flutter_templates/issues/59
As a developer, we need to prepare a CD process to build and deploy the staging iOS app to TestFlight.
Write WIKI for `iOS Deployment Process`
n/a
> [#59] [Part 2] As a developer, I can have a CD process to build and deploy the iOS app to TestFlight

- scripts/setup.py
- scripts/test.py
https://github.com/nimblehq/flutter_templates/issues/49
When initializing the project via script with the PACKAGE_NAME containing the underscore symbol _ (example: co.nimblehq.example.nimblehq_github), we are not able to create the development provisioning profile (to run app on the real iOS device). It is because the bundle identifier is invalid according to [CFBundleIdentifier](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier): The bundle ID string must contain only alphanumeric characters (A–Z, a–z, and 0–9), hyphens (-), and periods (.)
**NOTE**: Android accepts the underscore symbol.
n/a
https://user-images.githubusercontent.com/60863885/169260881-89449918-14cb-4434-abfc-ab757b59880e.mp4
> [#49] Fix: Bundle identifier does not allow underscore in iOS

- .github/workflows/ios_deploy_to_app_store.yml
- .template/.github/workflows/ios_deploy_to_app_store.yml
- .template/.github/workflows/ios_deploy_to_testflight.yml
- .template/ios/fastlane/Fastfile
- .template/ios/fastlane/Managers/DistributionManager.rb
https://github.com/nimblehq/flutter_templates/issues/60
As a developer, we need to prepare a CD process to build and deploy the staging iOS app to App Store.
n/a
The workflow is tested in CI: https://github.com/nimblehq/flutter_templates/runs/6705133545?check_suite_focus=true
The fastlane command is tested in local:
```
~/Desktop/nimble/github/flutter_templates/.template/ios  develop !5  bundle exec fastlane build_and_upload_app_store_connect_app                                                                                       1 ✘  1m 26s  15:11:50 
[✔] 🚀 
[15:13:16]: ------------------------------
[15:13:16]: --- Step: default_platform ---
[15:13:16]: ------------------------------
[15:13:16]: Driving the lane 'ios build_and_upload_app_store_connect_app' 🚀
[15:13:16]: …
```
> [#60] As a developer, I can have a CD process to build and deploy the iOS app to App Store

- .template/lib/usecases/base/base_use_case.dart
- .template/lib/usecases/base/use_case_result.dart
https://github.com/nimblehq/flutter_templates/issues/89
To reduce the effort of creating the base use cases when initializing a project, the base use cases should be ready at the template level.
n/a
n/a
> [#89] Add base use cases

- .template/lib/di/interceptor/app_interceptor.dart
- .template/lib/di/provider/dio_provider.dart
- .template/lib/utils/wrappers/permission_wrapper.dart
- .template/pubspec.yaml
The generated project can't run because of broken code.
- Fix some broken code to ensure the generated project can run properly.
- Missing `_dio` parameter in `AppInterceptor`.
- No `injectable` integrated yet, we should remove it in `PermissionWrapper` and update it later.
The generated app can build and run locally ✅
> [Hotfix] Can not build generated project from release 1.3.0

- scripts/setup.py
- Solves #135
When running the script under python 3.8 or lower, the error `TypeError` will happens.
- The error happens because [Type Hinting Generic](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections) is for python 3.9 or newer. We need to remove it.
- Add `try catch` block to catch if there is similar issue like this.
Python 3.8:
Python 3.9:
> [#135] Fix: The script is failed at clean_up step on Python 3.8

- .template/README.md
- Solves #139
The unit test command in the README file is incorrect, therefore, we need to update it.
Update the unit test command in the README file from `$ fvm flutter test .` to `$ fvm flutter test`
> [#139] Fix unit test command in README file

- .template/android/app/src/main/AndroidManifest.xml
- Solves #138 
Config Manifest file to support running on Android 12+
Export `MainActivity` tag inside Manifest
> [#138] Export MainActivity to support running on Android 12+

- .github/workflows/android_deploy_production.yml
- .github/workflows/android_deploy_staging.yml
- .github/workflows/bump_version.yml
- .github/workflows/test.yml
- template/.github/workflows/android_deploy_production.yml
- template/.github/workflows/android_deploy_staging.yml
- template/.github/workflows/ios_deploy_to_app_store.yml
- template/.github/workflows/ios_deploy_to_testflight.yml
- template/.github/workflows/test.yml
- Solves #47
- Add 2 new workflows to build & deploy Android `Staging` & `Production` builds to Firebase App Distribution.
- Firebase apps for the Flutter Templates project: https://console.firebase.google.com/u/1/project/fluttertempates---staging/overview.
- Refactor: Add missing names to some Action steps in existing workflows.
- There are 2 workflow versions for each:
- `template` project's workflow 👉 for the generated project.
- root project's workflow (the mirrored workflow) 👉 to test the workflow on generated project & deploy the generated Flutter Templates for reference.
- To distribute apps to Firebase, we need to create & use a [`Service Account`](https://console.cloud.google.com/iam-admin/serviceaccounts?authuser=0&project=fluttertempates---staging) instead of the deprecated …
> [#47] As a developer, I can have a CD process to build and deploy the Android app to Firebase App Distribution

- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE/release_template.md
- README.md
- template/.github/PULL_REQUEST_TEMPLATE.md
- template/.github/PULL_REQUEST_TEMPLATE/release_template.md
- template/README.md
- Solves #172
- Rename repository name to flutter-templates.
- Update README & wiki to follow the new name.
- Add `Wiki` link in the root README.
- I tried to find all related strings in the repository related to the repository name and renamed them to `flutter-templates`.
- The rest of `flutter_templates` belongs to the `template` project name & imports. We need to keep using `flutter_templates`.
New repo name: https://github.com/nimblehq/flutter-templates ✅ 
The template is being generated properly & the generated app is buildable & testable https://github.com/nimblehq/flutter-templates/actions/runs/4373243729/jobs/7651168442 ✅
> [#172] Rename repository name to "flutter-templates"

- .github/wiki/Deployment.md
- .github/workflows/android_deploy_production.yml
- .github/workflows/android_deploy_production_to_playstore.yml
- .github/workflows/android_deploy_staging.yml
- .github/workflows/bump_version.yml
- .github/workflows/test.yml
- template/.github/workflows/android_deploy_production.yml
- template/.github/workflows/android_deploy_production_to_playstore.yml
- template/.github/workflows/android_deploy_staging.yml
- template/.github/workflows/bump_version.yml
- template/.github/workflows/ios_deploy_to_app_store.yml
- template/.github/workflows/ios_deploy_to_testflight.yml
- template/.github/workflows/test.yml
- template/.github/workflows/whatsnew/whatsnew-en-US
- Solves #61
- Add a new workflow to build & deploy the Android `Production` release AppBundle to Play Store.
- Firebase apps for the Flutter Templates project: https://console.firebase.google.com/u/1/project/fluttertempates---staging/overview.
- Add wiki for the Android app publishing.
- There are 2 workflow versions for each:
- `template` project's workflow 👉 for the generated project.
- root project's workflow (the mirrored workflow) 👉 to test the workflow on generated project & deploy the generated Flutter Templates for reference.
- Use [`flutter build appbundle`](https://docs.flutter.dev/deployment/android#build-an-app-bundle) to build AppBundle for Play Store publishing.
- To upload the build to Play Store, we need to create & use a [`Service …
> [#61] As a developer, I can have a CD process to build and deploy the Android app to Play Store

- bricks/template/__brick__/template/ios/Runner.xcodeproj/project.pbxproj
- bricks/template/__brick__/template/ios/Runner/Info.plist
- bricks/template/__brick__/template/ios/fastlane/Constants/Constants.rb
- Solves #157
- Config `app_name`, `package_name` and `project_name` for iOS module dynamically so we can be able to generate a new project with the desired name.
- [Convention reference](https://github.com/felangel/mason/tree/master/packages/mason_cli#built-in-lambdas)
- Replace `Flutter Templates` with `app_name`, which follows title case convention
- Replace `co.nimblehq.flutter.template` with `package_name`, which follow dot case convention
- Replace `flutter_templates` with `project_name`, which follows snake case convention
Log:
```
~/Desktop/nimble/github/flutter_templates  feature/157-…ule-to-mason !3  mason make template -o generated/                                                                                            64 ✘  flutter_templates   10:42:10 
? Package …
```
> [#157] [Generate project with Mason] Migrate iOS project module generating step

- .github/workflows/android_deploy_production.yml
- .github/workflows/android_deploy_production_to_playstore.yml
- .github/workflows/android_deploy_staging.yml
- .github/workflows/bump_version.yml
- .github/workflows/ios_deploy_staging_to_firebase.yml
- .github/workflows/test.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/bump_version.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_staging_to_firebase.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_app_store.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_testflight.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/test.yml
- mason-config.json
- Solves #184
- Replace the Python script.
- Update necessary CI/CD workflows to use the new script:
- [test.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/test.yml).
- [android_deploy_staging.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/android_deploy_staging.yml)
- [android_deploy_production_to_playstore.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/android_deploy_production_to_playstore.yml)
- [android_deploy_production.yml](https://github.com/nimblehq/flutter-templates/blob/develop/.github/workflows/android_deploy_production.yml)
- According to the Mason documentation, [any variables which aren't specified as command line args will be …
> [#184] [Generate project with Mason] Update necessary CI/CD workflows to use the new script

- .github/workflows/android_deploy_production.yml
- .github/workflows/android_deploy_production_to_playstore.yml
- .github/workflows/android_deploy_staging.yml
- .github/workflows/ios_deploy_staging_to_firebase.yml
- .github/workflows/test.yml
- Solves #206
@manh-t found the bug in this PR https://github.com/nimblehq/flutter-templates/pull/203 and [has a fix](https://github.com/nimblehq/flutter-templates/pull/203/commits/2a29fb282e2077029ff9ff11eab9fd637e070d71) to bypass the issue. However, we just need to remove 1 more `sample` folder as `flutter_templates` has been moved to the root.
The workflows will work on the root project instead of the `sample`.
`flutter analyze .` command is back to pass ✅ 
https://github.com/nimblehq/flutter-templates/actions/runs/5154106600/jobs/9282150402?pr=207
> [#206] Fix: "flutter analyze ." command in CI workflow reports issues with new "sample" project folder

- .github/workflows/generate_sample.yml
- Solves #210 
- Update the `generate_sample.yml` workflow to check out the repository under the `bot-nimble` user with `WIKI_ACTION_TOKEN`.
- Add `bot-nimble` user into [Allow specified actors to bypass required pull requests](https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/) config .
- There are several ways to bypass this issue, such as: 
- Using [Allow specified actors to bypass required pull requests](https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/).
- Using a helper GA https://github.com/CasperWA/push-protected.
The first way should be an official & safe way to go, so I decided to add this config to `develop` branch config 🏁 
https://github.com/nimblehq/flutter-templates/actions/runs/5471311516/jobs/9962341094 is …
> [#210] Fix: generating sample project is failing to push changes to develop (protected branch)

- .github/workflows/generate_sample.yml
- Solves #212
- Skip git push action if there are no changes from the sample project.
- Run the `generate sample project` workflow on the `merge commit` only to [avoid the status check to fail on `develop` after pushing the generated project commit](https://github.com/nimblehq/flutter-templates/commit/82144a0f043bec6c2a48fa743987aa78375e0b2f).
- Use `git status sample --porcelain | wc -l` to detect `file changed count` in the `sample` project folder.
- Check and run the `Commit & push the sample project changes` step if has changed.
- To check a commit is the merge commit, use `if: ${{ contains(github.event.head_commit.message, 'Merge pull request') || (github.event.head_commit.author.email != 'luong@nimblehq.co') }}`.
- **Skip git push action if there are no changes from the sample …
> [Chore] Improve: skip git push action if there are no changes from the sample project

- .github/CODEOWNERS
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/CODEOWNERS
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production_to_playstore.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_staging.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/bump_version.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_staging_to_firebase.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_app_store.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_testflight.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/test.yml
- Solves #200
- Fix: disable variable replacement by using `mustacheCase` https://github.com/felangel/mason/issues/367
This issue has been raised by other develops:
- https://github.com/felangel/mason/issues/160
- https://github.com/felangel/mason/issues/367
The best solution, for now, is using [mustacheCase](https://docs.brickhub.dev/brick-syntax#built-in-lambdas) to let `mason` generates mustache syntax for those workflow variables instead of understanding them as variables to replace ✅  
The final update will look like this:
```
${{ secrets.GITHUB_TOKEN }}
```
👇 
```
${{#mustacheCase}}secrets.GITHUB_TOKEN{{/mustacheCase}}
```
The workflows in generated project have variable params configured correctly. For example:
- `bump_version.yml`
- `android_deploy_production.yml`
> [#200] Fix: The new project generator with Mason removes all variable params with ${{ }} format in workflows

- .github/workflows/test.yml
- Solves #222
After testing the newly generated project has passed, we need a job to generate the Mason bundles, then commit and push in cases there're any changes.
This PR is to create that automated job of the CI workflow.
According to the requirement, we should create a new workflow (`generate_mason_bundle.yml`). However, if we create a brand new workflow, we will need to use [the `workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) to trigger the `generate_mason_bundle.yml` workflow inside the `test.yml` workflow. That approach still resolves our issue, but it will be overused in this case.
According to [this document](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequis …
> [#222] Add new workflow to automate the mason bundle updating process after modifying the bundle config

- .github/workflows/ios_deploy_staging_to_firebase.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_staging_to_firebase.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_app_store.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_to_testflight.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/ios/fastlane/Constants/Environments.rb
- bricks/template/__brick__/{{project_name.snakeCase()}}/ios/fastlane/Fastfile
- sample/ios/fastlane/Fastfile
- sample/pubspec.lock
- Solves #241
I add the `$GITHUB_RUN_NUMBER` as the build number for iOS when building the app.
I add the `$GITHUB_RUN_NUMBER` as the build number for iOS when building the app for both `/.github/workflows/ios_deploy_staging_to_firebase.yml` and `/bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/ios_deploy_staging_to_firebase.yml`
[Build with run number `45`](https://github.com/nimblehq/flutter-templates/actions/runs/5721838341/job/15504015968?pr=250)
> [#241] [iOS] Set "build-number" by "$GITHUB_RUN_NUMBER" when building the app bundle

- .github/workflows/android_deploy_production_to_playstore.yml
- bricks/template/__brick__/{{project_name.snakeCase()}}/.github/workflows/android_deploy_production_to_playstore.yml
- Solves #229
- Add a new step (which was missed from https://github.com/nimblehq/flutter-templates/pull/251) to set up release signing configs: keystore & signing.properties.
- This step is needed only when building the `release` build.
- We must use `base64` to encode and decode the keystore & signing.properties to ensure the binary file content.
https://github.com/nimblehq/flutter-templates/actions/runs/5722187525/job/15504868438 ✅
> [#229] [Android] Add missing signing config in CD workflows

- .github/workflows/android_deploy_production.yml
- .github/workflows/android_deploy_staging.yml
- .github/workflows/configs/changelog-config.json
- .github/workflows/ios_deploy_staging_to_firebase.yml
- bricks/template/__brick__/.github/workflows/android_deploy_production.yml
- bricks/template/__brick__/.github/workflows/android_deploy_staging.yml
- bricks/template/__brick__/.github/workflows/configs/changelog-config.json
- bricks/template/__brick__/.github/workflows/ios_deploy_staging_to_firebase.yml
- bricks/template/__brick__/ios/fastlane/Constants/Environments.rb
- bricks/template/__brick__/ios/fastlane/Fastfile
- sample/.github/workflows/android_deploy_production.yml
- sample/.github/workflows/android_deploy_staging.yml
- sample/.github/workflows/configs/changelog-config.json
- sample/.github/workflows/ios_deploy_staging_to_firebase.yml
- sample/ios/fastlane/Constants/Environments.rb
- sample/ios/fastlane/Fastfile
- Close #198 
- Use `mikepenz/release-changelog-builder-action` to generate change log
- Find and use HEAD commit for prudction build
- Apply `Limit changelog to the latest pull request only` for staging
- Add `changelog-config.json` file
- I was trying to use `echo "RELEASE_NOTE_CONTENT="$((git log -1 --merges | grep "\[") | grep . && echo "" || echo $(git log -1 --merges --format=%B))""` for staging flow (android and iOS)
and  Add `echo "RELEASE_NOTE_CONTENT="$(git log --merges --pretty=%B $(git describe --abbrev=0 --tags)..HEAD | grep "\[")""` for production flow (Android only)
But neither of them works (showing empty value)
- Trying with `[8BitJonny/gh-get-current-pr](https://github.com/8BitJonny/gh-get-current-pr) is better, but it still does not meet our expectations. It is only …
> [#198] Generate and add "release notes" when distributing new builds on Firebase (staging and production)
